export const TRIAL_ABSENTEE_PLAYERS = [
  "Abhradip Mondal",
  "Kaustuv paul",
  "Kuntal Ghosh",
  "Rohan Majumder",
  "ARIJITROY",
  "Debabrata Ghosh",
  "Debalin Das",
  "Dip Chatterjee",
  "Kaustav Dhara",
  "Md Yusuf Alam",
  "Rajbir paul",
  "Rajkumar Singha",
  "Ranojoy Chatterjee",
  "Shubhradip saha",
  "Snehasish koley",
  "Sourin Ghosh",
  "Subhojeet Manna",
  "Aayush Kumar",
  "Aman Paramanik",
  "Ardhendu Sahu",
  "Arup Mondal",
  "Arya Chowdhury",
  "Ayushman Ghosh",
  "Krish Sonar",
  "Nirnay Saha",
  "Sagnik Das",
  "Sandeep Bhattacharjee",
  "Sekh Tajuddin Ahamed",
  "Spandan Sinharoy",
  "Anik kumar arya",
  "Lokesh Chauhan",
  "Pawandev Mahato",
  "RAJESH MONDAL",
  "Ritwik Paladhi",
  "Ronit Tantubai",
  "S Siddharth",
  "SAYAN DEY SARKAR",
  "Sk Saqibul Islam",
  "SWARNAVA PAUL",
] as const;
