// Shared mock data for all Next.js API dummy routes

export const MOCK_SESSION_ID = "session_ucl_2026";

export const MOCK_TEAMS = [
  {
    id: "t01",
    slug: "arsenal-fc",
    name: "Arsenal FC",
    shortCode: "ARS",
    domain: "arsenal.com",
    pointsTotal: 1000,
    pointsSpent: 250,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t02",
    slug: "fc-inter-milan",
    name: "FC Inter Milan",
    shortCode: "INT",
    domain: "inter.it",
    pointsTotal: 1000,
    pointsSpent: 180,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t03",
    slug: "sl-benfica",
    name: "S.L. Benfica",
    shortCode: "BEN",
    domain: "slbenfica.pt",
    pointsTotal: 1000,
    pointsSpent: 0,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t04",
    slug: "chelsea-fc",
    name: "Chelsea FC",
    shortCode: "CHE",
    domain: "chelseafc.com",
    pointsTotal: 1000,
    pointsSpent: 320,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t05",
    slug: "manchester-city",
    name: "Manchester City",
    shortCode: "MCI",
    domain: "mancity.com",
    pointsTotal: 1000,
    pointsSpent: 410,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t06",
    slug: "fc-barcelona",
    name: "FC Barcelona",
    shortCode: "BAR",
    domain: "fcbarcelona.com",
    pointsTotal: 1000,
    pointsSpent: 150,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t07",
    slug: "paris-saint-germain",
    name: "Paris Saint-Germain",
    shortCode: "PSG",
    domain: "psg.fr",
    pointsTotal: 1000,
    pointsSpent: 290,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t08",
    slug: "newcastle-united",
    name: "Newcastle United",
    shortCode: "NEW",
    domain: "nufc.co.uk",
    pointsTotal: 1000,
    pointsSpent: 0,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t09",
    slug: "atletico-de-madrid",
    name: "Atletico de Madrid",
    shortCode: "ATL",
    domain: "atleticodemadrid.com",
    pointsTotal: 1000,
    pointsSpent: 200,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t10",
    slug: "juventus-fc",
    name: "Juventus FC",
    shortCode: "JUV",
    domain: "juventus.com",
    pointsTotal: 1000,
    pointsSpent: 130,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t11",
    slug: "liverpool-fc",
    name: "Liverpool FC",
    shortCode: "LIV",
    domain: "liverpoolfc.com",
    pointsTotal: 1000,
    pointsSpent: 370,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t12",
    slug: "real-madrid",
    name: "Real Madrid",
    shortCode: "RMA",
    domain: "realmadrid.com",
    pointsTotal: 1000,
    pointsSpent: 500,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t13",
    slug: "borussia-dortmund",
    name: "Borussia Dortmund",
    shortCode: "BVB",
    domain: "bvb.de",
    pointsTotal: 1000,
    pointsSpent: 80,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t14",
    slug: "sporting-cp",
    name: "Sporting CP",
    shortCode: "SCP",
    domain: "sporting.pt",
    pointsTotal: 1000,
    pointsSpent: 0,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t15",
    slug: "ac-milan",
    name: "AC Milan",
    shortCode: "ACM",
    domain: "acmilan.com",
    pointsTotal: 1000,
    pointsSpent: 220,
    sessionId: MOCK_SESSION_ID,
  },
  {
    id: "t16",
    slug: "fc-bayern-munchen",
    name: "FC Bayern München",
    shortCode: "BAY",
    domain: "fcbayern.com",
    pointsTotal: 1000,
    pointsSpent: 460,
    sessionId: MOCK_SESSION_ID,
  },
];

export const MOCK_PLAYERS = [
  {
    id: "p01",
    name: "Erling Haaland",
    position: "ST",
    basePrice: 150,
    status: "SOLD",
    teamId: "t05",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 200,
  },
  {
    id: "p02",
    name: "Kylian Mbappé",
    position: "LW",
    basePrice: 150,
    status: "SOLD",
    teamId: "t12",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 250,
  },
  {
    id: "p03",
    name: "Vinicius Jr.",
    position: "LW",
    basePrice: 130,
    status: "SOLD",
    teamId: "t12",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 180,
  },
  {
    id: "p04",
    name: "Jude Bellingham",
    position: "CAM",
    basePrice: 120,
    status: "SOLD",
    teamId: "t12",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 220,
  },
  {
    id: "p05",
    name: "Bukayo Saka",
    position: "RW",
    basePrice: 110,
    status: "SOLD",
    teamId: "t01",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 150,
  },
  {
    id: "p06",
    name: "Mohamed Salah",
    position: "RW",
    basePrice: 120,
    status: "SOLD",
    teamId: "t11",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 170,
  },
  {
    id: "p07",
    name: "Harry Kane",
    position: "ST",
    basePrice: 130,
    status: "SOLD",
    teamId: "t16",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 180,
  },
  {
    id: "p08",
    name: "Rodri",
    position: "CM",
    basePrice: 100,
    status: "SOLD",
    teamId: "t05",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 130,
  },
  {
    id: "p09",
    name: "Phil Foden",
    position: "CAM",
    basePrice: 110,
    status: "SOLD",
    teamId: "t05",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 140,
  },
  {
    id: "p10",
    name: "Lamine Yamal",
    position: "RW",
    basePrice: 100,
    status: "SOLD",
    teamId: "t06",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 130,
  },
  {
    id: "p11",
    name: "Pedri",
    position: "CM",
    basePrice: 90,
    status: "SOLD",
    teamId: "t06",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 110,
  },
  {
    id: "p12",
    name: "Virgil van Dijk",
    position: "CB",
    basePrice: 90,
    status: "SOLD",
    teamId: "t11",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 120,
  },
  {
    id: "p13",
    name: "Trent Alexander-Arnold",
    position: "RB",
    basePrice: 100,
    status: "SOLD",
    teamId: "t11",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 130,
  },
  {
    id: "p14",
    name: "Antoine Griezmann",
    position: "CAM",
    basePrice: 90,
    status: "SOLD",
    teamId: "t09",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 110,
  },
  {
    id: "p15",
    name: "Alisson Becker",
    position: "GK",
    basePrice: 80,
    status: "SOLD",
    teamId: "t11",
    sessionId: MOCK_SESSION_ID,
    transactionAmount: 80,
  },
  {
    id: "p16",
    name: "Nicolás González",
    position: "LW",
    basePrice: 70,
    status: "IN_AUCTION",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p17",
    name: "Florian Wirtz",
    position: "CAM",
    basePrice: 110,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p18",
    name: "Jamal Musiala",
    position: "CAM",
    basePrice: 110,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p19",
    name: "Ademola Lookman",
    position: "LW",
    basePrice: 70,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p20",
    name: "Nico Williams",
    position: "LW",
    basePrice: 80,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p21",
    name: "Dani Carvajal",
    position: "RB",
    basePrice: 70,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p22",
    name: "Rúben Dias",
    position: "CB",
    basePrice: 80,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p23",
    name: "William Saliba",
    position: "CB",
    basePrice: 80,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p24",
    name: "Bernardo Silva",
    position: "CM",
    basePrice: 90,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p25",
    name: "Joshua Kimmich",
    position: "CM",
    basePrice: 90,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p26",
    name: "Leroy Sané",
    position: "RW",
    basePrice: 80,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p27",
    name: "Marcus Rashford",
    position: "LW",
    basePrice: 80,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p28",
    name: "Rafael Leão",
    position: "LW",
    basePrice: 90,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p29",
    name: "Mike Maignan",
    position: "GK",
    basePrice: 70,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
  {
    id: "p30",
    name: "Gianluigi Donnarumma",
    position: "GK",
    basePrice: 70,
    status: "UNSOLD",
    teamId: null,
    sessionId: MOCK_SESSION_ID,
    transactionAmount: null,
  },
];

export const MOCK_TRANSACTIONS = MOCK_PLAYERS.filter(
  (p) => p.status === "SOLD" && p.teamId,
).map((p, i) => ({
  id: `tx${String(i + 1).padStart(2, "0")}`,
  playerId: p.id,
  teamId: p.teamId!,
  sessionId: MOCK_SESSION_ID,
  amount: p.transactionAmount!,
  createdAt: new Date(Date.now() - (15 - i) * 60_000).toISOString(),
  player: { id: p.id, name: p.name, position: p.position },
  team: MOCK_TEAMS.find((t) => t.id === p.teamId)!,
}));
